name: Print Github context manually
on: workflow_dispatch
jobs:
  print_github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: |
          echo "${{github}}"
